protected/models/Client.php
<?php

/**
 * This is the model class for table "pm_client".
 *
 * The followings are the available columns in table 'pm_client':
 * @property integer $client_id
 * @property string $client_name
 * @property string $client_address
 * @property string $client_phone
 * @property integer $crtd_by
 * @property string $crtd_dt
 * @property integer $updt_by
 * @property string $updt_dt
 * @property integer $updt_cnt
 *
 * The followings are the available model relations:
 * @property PmClientContact[] $pmClientContacts
 * @property PmProject[] $pmProjects
 */
class Client extends PMActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'pm_client';
	}

        
          public function scopes() 
        {
                return array(
                    'byName' => array('order' => 'client_name ASC'),
                  );
        }
	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('client_name', 'required'),
			array('crtd_by, updt_by, updt_cnt', 'numerical', 'integerOnly'=>true),
			array('client_name, client_phone', 'length', 'max'=>255),
			array('client_address,crtd_dt, updt_dt', 'safe'),
			array('client_name','unique'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('client_name, client_address, client_phone', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'pmClientContacts' => array(self::HAS_MANY, 'PmClientContact', 'client_id'),
			'pmProjects' => array(self::HAS_MANY, 'PmProject', 'client_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'client_id' => 'Client',
			'client_name' => 'Name',
			'client_address' => 'Address',
			'client_phone' => 'Phone',
			'crtd_by' => 'Crtd By',
			'crtd_dt' => 'Crtd Dt',
			'updt_by' => 'Updt By',
			'updt_dt' => 'Updt Dt',
			'updt_cnt' => 'Updt Cnt',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('client_id',$this->client_id);
		$criteria->compare('client_name',$this->client_name,true);
		$criteria->compare('client_address',$this->client_address,true);
		$criteria->compare('client_phone',$this->client_phone,true);
		$criteria->compare('crtd_by',$this->crtd_by);
		$criteria->compare('crtd_dt',$this->crtd_dt,true);
		$criteria->compare('updt_by',$this->updt_by);
		$criteria->compare('updt_dt',$this->updt_dt,true);
		$criteria->compare('updt_cnt',$this->updt_cnt);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
                        'sort'=>array(
			    'defaultOrder' => 'client_name ASC',
		        'attributes'=>array(
		            	
		            '*',
		        ),
		    ),
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Client the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/ClientController.php
<?php

class ClientController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/column1';

/**
* @return array action filters
*/
public function filters()
{
return array(
'accessControl', // perform access control for CRUD operations
);
}

/**
* Specifies the access control rules.
* This method is used by the 'accessControl' filter.
* @return array access control rules
*/
public function accessRules()
{
return array(
array('allow',  // allow all users to perform 'index' and 'view' actions
'actions'=>array('index','view'),
'users'=>array('admin'),
),
array('allow', // allow authenticated user to perform 'create' and 'update' actions
'actions'=>array('admin','delete','create','update'),
'users'=>array('admin'),
),
//array('allow', // allow admin user to perform 'admin' and 'delete' actions
//'actions'=>array('admin','delete'),
//'users'=>array('admin'),
//),
array('deny',  // deny all users
'users'=>array('*'),
),
);
}

/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
public function actionView($id)
{
	//$this->render('view',array(
	//'model'=>$this->loadModel($id),
	//));
	EQuickDlgs::render('view',array('model'=>$this->loadModel($id)));
}

/**
* Creates a new model.
* If creation is successful, the browser will be redirected to the 'view' page.
*/
public function actionCreate()
{
$model=new Client;

// Uncomment the following line if AJAX validation is needed
$this->performAjaxValidation($model);

if(isset($_POST['Client']))
{
$model->attributes=$_POST['Client'];
if($model->save())
	{
		EQuickDlgs::checkDialogJsScript();
		$this->redirect(array('admin','id'=>$model->client_id));
		//$this->redirect(array('admin'));
	}
	
}

EQuickDlgs::render('create',array(
'model'=>$model,
));
}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
public function actionUpdate($id)
{
$model=$this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Client']))
{
$model->attributes=$_POST['Client'];
if($model->save())
	//$this->redirect(array('view','id'=>$model->client_id));
	{
		//$this->redirect(array('admin'));
		EQuickDlgs::checkDialogJsScript();
		$this->redirect(array('admin','id'=>$model->client_id));
	}
	
}

EQuickDlgs::render('update',array(
'model'=>$model,
));
}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
if(Yii::app()->request->isPostRequest)
{
// we only allow deletion via POST request
$this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
if(!isset($_GET['ajax']))
$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
}
else
throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
}

/**
* Lists all models.
*/
public function actionIndex()
{
//$dataProvider=new CActiveDataProvider('Client');
//$this->render('index',array(
//'dataProvider'=>$dataProvider,
//));
$this->actionAdmin();
}

/**
* Manages all models.
*/
public function actionAdmin()
{
$model=new Client('search');
$model->unsetAttributes();  // clear any default values
if(isset($_GET['Client']))
$model->attributes=$_GET['Client'];

$this->render('admin',array(
'model'=>$model,
));
}



/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=Client::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='client-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}
}

protected/views/client/_form.php
<?php
/* @var $this ClientContactController */
/* @var $model ClientContact */
/* @var $form CActiveForm */
?>

<div class="form wide">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'client-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>true,
)); ?>

	<!--<p class="note">Fields with <span class="required">*</span> are required.</p>-->

	<?php //echo $form->errorSummary($model); ?>


	<div class="row col2">
		<?php echo $form->labelEx($model,'client_name'); ?>
		<?php echo $form->textField($model,'client_name',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'client_name'); ?>
	</div>
	
	
	
	
	<div class="row col2">
		<?php echo $form->labelEx($model,'client_phone'); ?>
		<?php echo $form->textField($model,'client_phone',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'client_phone'); ?>
	</div>

	<div style="clear:both"></div>
	<div class="row col2">
		<?php echo $form->labelEx($model,'client_address'); ?>
		<?php echo $form->textArea($model,'client_address',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'client_address'); ?>
	</div>
	
	<div style="clear:both"></div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save',array('class' => 'btn')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/client/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldRow($model,'client_id',array('class'=>'span5')); ?>

		<?php echo $form->textFieldRow($model,'client_name',array('class'=>'span5','maxlength'=>255)); ?>

		<?php echo $form->textAreaRow($model,'client_address',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

		<?php echo $form->textFieldRow($model,'client_phone',array('class'=>'span5','maxlength'=>255)); ?>

		<?php echo $form->textFieldRow($model,'crtd_by',array('class'=>'span5')); ?>

		<?php echo $form->textFieldRow($model,'crtd_dt',array('class'=>'span5')); ?>

		<?php echo $form->textFieldRow($model,'updt_by',array('class'=>'span5')); ?>

		<?php echo $form->textFieldRow($model,'updt_dt',array('class'=>'span5')); ?>

		<?php echo $form->textFieldRow($model,'updt_cnt',array('class'=>'span5')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/client/_view.php
<div class="view">

		<b><?php echo CHtml::encode($data->getAttributeLabel('client_id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->client_id),array('view','id'=>$data->client_id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('client_name')); ?>:</b>
	<?php echo CHtml::encode($data->client_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('client_address')); ?>:</b>
	<?php echo CHtml::encode($data->client_address); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('client_phone')); ?>:</b>
	<?php echo CHtml::encode($data->client_phone); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('crtd_by')); ?>:</b>
	<?php echo CHtml::encode($data->crtd_by); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('crtd_dt')); ?>:</b>
	<?php echo CHtml::encode($data->crtd_dt); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('updt_by')); ?>:</b>
	<?php echo CHtml::encode($data->updt_by); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('updt_dt')); ?>:</b>
	<?php echo CHtml::encode($data->updt_dt); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('updt_cnt')); ?>:</b>
	<?php echo CHtml::encode($data->updt_cnt); ?>
	<br />

	*/ ?>

</div>

protected/views/client/admin.php
<?php
$this->breadcrumbs=array(
	'Clients'=>array('index'),
	'Manage',
);

$this->menu=array(
array('label'=>'List Client','url'=>array('index')),
array('label'=>'Create Client','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
$('.search-form').toggle();
return false;
});
$('.search-form form').submit(function(){
$.fn.yiiGridView.update('client-grid', {
data: $(this).serialize()
});
return false;
});
");
?>

<!--<h1>Manage Clients</h1>-->

<!--<p>
	You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>
		&lt;&gt;</b>
	or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>-->

<!--<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
	<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div>--><!-- search-form -->


<?php
//$this->widget(
//'bootstrap.widgets.TbButton',
//array(
//'label' => 'New client',
 //'url' => 'client/create',
//)
//);
?>

<div class="btnalign">
<?php
EQuickDlgs::iframeButton(
    array(
        'controllerRoute' => 'client/create',
        'dialogTitle' => 'Create client',
        'dialogWidth' => '80%',
        'dialogHeight' => '500',
        'openButtonText' => 'New client',
        'closeButtonText' => 'Close',
		'id' => 'newClient',
		'openButtonHtmlOptions'=>array('class'=>'btn',),
		//'renderOpenButton' => false,
        'closeOnAction' =>true, //important to invoke the close action in the actionCreate
        'refreshGridId' => 'client-grid', //the grid with this id will be refreshed after closing
		'iframeHtmlOptions' => array(
                                                            'width' => '100%',
                                                            'height' => '100%',
                                                    ),
    )
);
?>
</div>


<?php 
$uniqid=md5(uniqid());
$this->widget('bootstrap.widgets.TbExtendedGridView',array(
'id'=>'client-grid',
'dataProvider'=>$model->search(),
'filter'=>$model,
'type' => 'striped bordered',
'columns'=>array(
		//'client_id',
		array(
            'header'=>'#',
            'value'=>'$this->grid->dataProvider->pagination->currentPage * $this->grid->dataProvider->pagination->pageSize + ($row+1)',
			'class'=>'bootstrap.widgets.TbRelationalColumn',
			'url' => $this->createUrl('clientContact/loadByClient'),
			'uniqid'=>$uniqid,
			'afterAjaxUpdate' => 'js:function(tr,rowid,data){
					}'
        ),
		
		
                 array(
                     'name'=>'client_name',
                     'value'=>'$data->client_name',
                     'htmlOptions' => array('style'=>'width:200px'), 
                 ),
		
    array(
                     'name'=>'client_phone',
                     'value'=>'$data->client_phone',
                     'htmlOptions' => array('style'=>'width:100px'), 
                 ),
		'client_address',
		array(
            'class'=>'EJuiDlgsColumn',
			'htmlOptions' => array('style'=>'width:60px'),

			'deleteButtonUrl'=>'Yii::app()->createUrl("/client/delete", array("id" => $data->client_id))',
			
           	//'updateButtonImageUrl'=>Yii::app()->baseUrl .'images/viewdetaildialog.png',
            'buttons'=>array(
                        'view'=>
                             array(
                        'label'=>'ajax dialog view',
                    ),
                            ),
							'viewDialog'=>array(
             'controllerRoute' => 'client/view', //=default
             'actionParams' => array('id' => '$data->primaryKey'), //=default
             'dialogTitle' => 'View client',
			 'closeOnAction' => true,
			 'refreshGridId' => 'client-grid',
                         'hideTitleBar' => false, 
              'dialogWidth' => '80%',
        		'dialogHeight' => '300',
        ),
		'updateDialog'=>array(
             'controllerRoute' => 'client/update', //=default
             'actionParams' => array('id' => '$data->primaryKey'), //=default
             'dialogTitle' => 'Update client',
			 'closeOnAction' => true,
			  'refreshGridId' => 'client-grid',
			  'dialogWidth' => '80%',
        		'dialogHeight' => '500',
                         'hideTitleBar' => false,
						 'iframeHtmlOptions' => array(
                                                            'width' => '100%',
                                                            'height' => '450',
                                                    ), 
             //'dialogWidth' => 800, //use the value from the dialog config
             //'dialogHeight' => 600,
        ),
		
           
        ),
		/*'crtd_by',
		'crtd_dt',
		
		'updt_by',
		'updt_dt',
		'updt_cnt',
		*/
//array(
//'class'=>'bootstrap.widgets.TbButtonColumn',
//),
),
)); ?>

protected/views/client/create.php
<?php
$this->breadcrumbs=array(
	'Clients'=>array('index'),
	'Create',
);

$this->menu=array(
array('label'=>'List Client','url'=>array('index')),
array('label'=>'Manage Client','url'=>array('admin')),
);
?>

<!--<h1>Create Client</h1>-->

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/client/index.php
<?php
$this->breadcrumbs=array(
	'Clients',
);

$this->menu=array(
array('label'=>'Create Client','url'=>array('create')),
array('label'=>'Manage Client','url'=>array('admin')),
);
?>

<h1>Clients</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
'dataProvider'=>$dataProvider,
'itemView'=>'_view',
)); ?>

protected/views/client/update.php
<?php
$this->breadcrumbs=array(
	'Clients'=>array('index'),
	$model->client_id=>array('view','id'=>$model->client_id),
	'Update',
);

	$this->menu=array(
	array('label'=>'List Client','url'=>array('index')),
	array('label'=>'Create Client','url'=>array('create')),
	array('label'=>'View Client','url'=>array('view','id'=>$model->client_id)),
	array('label'=>'Manage Client','url'=>array('admin')),
	);
	?>

	<!--<h1>Update Client <?php //echo $model->client_id; ?></h1>-->

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/client/view.php
<?php
$this->breadcrumbs=array(
	'Clients'=>array('index'),
	$model->client_id,
);

$this->menu=array(
array('label'=>'List Client','url'=>array('index')),
array('label'=>'Create Client','url'=>array('create')),
array('label'=>'Update Client','url'=>array('update','id'=>$model->client_id)),
array('label'=>'Delete Client','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->client_id),'confirm'=>'Are you sure you want to delete this item?')),
array('label'=>'Manage Client','url'=>array('admin')),
);
?>

<!--<h1>View Client #<?php //echo $model->client_id; ?></h1>-->

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
'data'=>$model,
'attributes'=>array(
	//'client_id',
		'client_name',
		'client_address',
		'client_phone',
		
),
)); ?>